#!/usr/bin/env python3
# Modified 2026-09-02 for the cmux carousel build (cmux-carousel-ui CONTRACT, harness H3; rows 11, 85, 116, 118, 124, 127, 132).
"""Build a fixture data root for H3, to be injected via CMUX_CAROUSEL_DATA_ROOT.

Why a fixture root and not a temp HOME: a probe on the Mac proved both Swift
home-directory APIs ignore a HOME override, so the temp-HOME seam the contract
originally specified cannot work. Sources/Carousel/Data/CarouselDataRoot.swift is the
only seam, and this script writes the tree it points at.

EVERY FIXTURE CARRIES A CANARY, and the canary is a NAME the UI must display, not a
count. A count-only assertion passes when the fixture failed to bite and the UI is
showing the real Hive sessions instead -- the exact way a data-driven row goes green
without ever reading the fixture. Asserting a name the real data cannot contain is
what makes the injection falsifiable.

The NEGATIVE CONTROL is not optional and is generated by `--empty`: a root with no
sessions at all, against which the UI must render the empty state AND must show none
of the real sessions. A provider that silently falls back to the real root passes
every positive control and fails nothing without this.

Fixtures live in the test target's temporary area and never ship.

  make_fixture_root.py <dir> --sessions N [--subagents N] [--nested] [--running N]
  make_fixture_root.py <dir> --empty
  make_fixture_root.py <dir> --preset {zero,one,two,three,forty,out-of-scope,unmounted}
"""

import argparse
import json
import os
import time

CANARY_PREFIX = "CANARY-FIXTURE"


def write(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        json.dump(obj, fh, indent=2)


def write_jsonl(path, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        for r in rows:
            fh.write(json.dumps(r) + "\n")


def build(root, sessions, subagents, nested, running, agent_kind, mounted):
    now = int(time.time())
    os.makedirs(os.path.join(root, "sessions"), exist_ok=True)
    os.makedirs(os.path.join(root, "statusline-snapshots"), exist_ok=True)
    made = []
    for i in range(sessions):
        sid = "%s-SESSION-%02d" % (CANARY_PREFIX, i)
        # The canary is the session NAME. It cannot occur in the real Hive root, so a
        # UI showing it is provably reading THIS fixture.
        write(os.path.join(root, "sessions", "%s.json" % sid), {
            "pid": 900000 + i,
            "sessionId": sid,
            "cwd": "/tmp/%s" % sid,
            "name": "%s-NAME-%02d" % (CANARY_PREFIX, i),
            "status": "running" if i < running else "idle",
            "kind": agent_kind,
            "startedAt": now - 60,
            "updatedAt": now,
            # D-4: the card-to-session join is the surface's tmux target and command.
            "tmux": {"session": "fixture-%02d" % i, "window": "0", "pane": "%d" % i},
            # D-9 / row 132: an unmounted workspace's surface has no live view, so it
            # is excluded from the card list and surfaced as a count instead.
            "mounted": bool(i < mounted) if mounted is not None else True,
        })
        # Row 76's statusline snapshot, per session, with the field row 120 proved real.
        write(os.path.join(root, "statusline-snapshots", "%s.json" % sid), {
            "session_id": sid,
            "model": {"id": "claude-fable-5-1",
                      "display_name": "%s-MODEL-%02d" % (CANARY_PREFIX, i)},
            "context_window": {"used_percentage": 63.4, "context_window_size": 200000,
                               "current_usage": {"input_tokens": 1, "output_tokens": 1}},
            # resets_at is a UNIX EPOCH INTEGER on the real payload, not an ISO-8601
            # string. Verified against a live capture on 2026-09-02; a fixture using a
            # string would let a formatter bug ship.
            "rate_limits": {"five_hour": {"used_percentage": 62, "resets_at": now + 3600},
                            "seven_day": {"used_percentage": 41, "resets_at": now + 86400}},
            "_carousel": {"captured_at": now, "host": "fixture", "schema": 1},
        })
        if subagents:
            slug = "-fixture"
            base = os.path.join(root, "projects", slug, sid, "subagents")
            for j in range(subagents):
                agent_id = "agent-%s-%02d-%02d" % (CANARY_PREFIX, i, j)
                # Row 11: the glob is agent-*.jsonl. A bare agent-* glob double-counts,
                # because each agent has a PAIRED .meta.json sitting beside it.
                write_jsonl(os.path.join(base, "%s.jsonl" % agent_id), [
                    {"role": "user", "content": "start"},
                    # Row 127: the agent-running signal is the last message's role plus
                    # the sibling .meta.json. A trailing assistant message reads idle;
                    # a trailing user message reads running.
                    {"role": "user" if j < running else "assistant", "content": "work"},
                ])
                meta = {
                    "agentId": agent_id,
                    "agentType": "%s-TYPE-%02d" % (CANARY_PREFIX, j),
                    "description": "%s-DESC-%02d" % (CANARY_PREFIX, j),
                    "spawnDepth": 0,
                }
                if nested and j > 0:
                    meta["parentAgentId"] = "agent-%s-%02d-00" % (CANARY_PREFIX, i)
                    meta["spawnDepth"] = 1
                write(os.path.join(base, "%s.meta.json" % agent_id), meta)
        made.append(sid)
    # The mirror stamp, so CarouselDataRoot reports a defined freshness rather than
    # .unknown. Fixtures are always fresh unless a test asks otherwise.
    with open(os.path.join(root, ".mirror-stamp"), "w") as fh:
        fh.write("host=fixture\nremote_root=fixture\ncompleted_epoch=%d\n" % now)
    return made


PRESETS = {
    # Row 116's three common cases plus the ones the contract names by number.
    "zero": dict(sessions=0, subagents=0, nested=False, running=0, agent_kind="claude", mounted=None),
    "one": dict(sessions=1, subagents=0, nested=False, running=1, agent_kind="claude", mounted=None),
    "two": dict(sessions=2, subagents=0, nested=False, running=1, agent_kind="claude", mounted=None),
    "three": dict(sessions=3, subagents=3, nested=True, running=1, agent_kind="claude", mounted=None),
    "forty": dict(sessions=1, subagents=40, nested=True, running=3, agent_kind="claude", mounted=None),
    # Row 124: a non-Claude surface must render a defined out-of-scope state, never a
    # broken card, and must claim no sub-agent or usage data it cannot read.
    "out-of-scope": dict(sessions=2, subagents=0, nested=False, running=1, agent_kind="codex", mounted=None),
    # Row 132: two workspaces, one mounted and one not.
    "unmounted": dict(sessions=2, subagents=0, nested=False, running=1, agent_kind="claude", mounted=1),
}


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("root")
    p.add_argument("--sessions", type=int, default=3)
    p.add_argument("--subagents", type=int, default=0)
    p.add_argument("--nested", action="store_true")
    p.add_argument("--running", type=int, default=1)
    p.add_argument("--agent-kind", default="claude")
    p.add_argument("--mounted", type=int, default=None)
    p.add_argument("--empty", action="store_true",
                   help="the mandatory negative control: a root with no sessions at all")
    p.add_argument("--preset", choices=sorted(PRESETS))
    args = p.parse_args()

    os.makedirs(args.root, exist_ok=True)
    if args.empty:
        os.makedirs(os.path.join(args.root, "sessions"), exist_ok=True)
        print("NEGATIVE CONTROL root at %s" % args.root)
        print("Assert BOTH: the carousel renders its empty state, AND it shows none of")
        print("the real Hive session names. A provider that silently falls back to the")
        print("real root passes every positive control and fails nothing without this.")
        return 0

    cfg = PRESETS[args.preset] if args.preset else dict(
        sessions=args.sessions, subagents=args.subagents, nested=args.nested,
        running=args.running, agent_kind=args.agent_kind, mounted=args.mounted)
    made = build(args.root, **cfg)
    print("fixture root: %s" % args.root)
    print("sessions: %d" % len(made))
    if made:
        print("CANARY the UI must display: %s-NAME-00" % CANARY_PREFIX)
        print("Assert that exact string, not a count. A count passes when the fixture")
        print("failed to bite and the UI is showing the real Hive sessions instead.")
    print("\nexport CMUX_CAROUSEL_DATA_ROOT=%s" % os.path.abspath(args.root))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
